# Generated by Django 5.1.2 on 2024-10-30 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Марка автомобиля',
                'verbose_name_plural': 'Марка автомобиля',
                'db_table': 'car_brand',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Модель')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car_app.carbrand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модель автомобиля',
                'db_table': 'car_model',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=250, verbose_name='VIN')),
                ('state_number', models.CharField(max_length=250, verbose_name='Гос номер')),
                ('year_issue', models.DateField(verbose_name='Год выпуска')),
                ('weight', models.CharField(max_length=250, verbose_name='Масса')),
                ('current_mileage', models.CharField(max_length=250, verbose_name='Текущий пробег')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Изображение автомобиля')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.carbrand', verbose_name='Марка автомобиля')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.carmodel', verbose_name='Модель автомобиля')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Автомобили',
                'verbose_name_plural': 'Автомобили',
                'db_table': 'cars',
            },
        ),
    ]
